#include <uf_defs.h>
#include <uf.h>
#include <uf_ui.h>
#include <uf_obj.h>
#include <uf_obj_types.h>
#include <NXOpen/NXException.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/Selection.hxx>
#include <NXOpen/CAM_NCGroup.hxx>
#include <NXOpen/INXObject.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Session.hxx>
#include <NXOpen/Validate_ValidationManager.hxx>

#include <NXOpen/CAM_CAMSetup.hxx>
#include <NXOpen/CAM_NCGroup.hxx>
#include <NXOpen/CAM_NCGroupCollection.hxx>

#include <NXOpen/ListingWindow.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXException.hxx>
#include <iostream>
#include <cctype>

#include <NXOpen/Callback.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_StringBlock.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>

using namespace NXOpen;
using std::exception;
using std::string;

#define _SECURE_SCL 0
//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\Program Files\my_menu.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: User
//              Version: NX 12
//              Date: 05-22-2018  (Format: mm-dd-yyyy)
//              Time: 21:12
//
//==============================================================================

#ifndef MY_MENU_H_INCLUDED
#define MY_MENU_H_INCLUDED

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport my_menu
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
	static Part * workpart;
	static Part *displayPart;

    my_menu();
	void set_values(NXString p_name, NXString p_iter, NXString p_start, bool p_toggle, char sym, bool state);
    //static void Show_my_menu();
    ~my_menu();
    int Show();
    //void RegisterWithMenu();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the my_menu.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int ok_cb();
    int cancel_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char *blockID);

	NXString p_name_return() const { return pr_name; };
	int p_iter_return() const { return pr_iter; };
	int p_start_return() const { return start_path_value; };
	bool cancel_return()const { return canceled; }
	bool toggle_state() const { return toggle_val; }
	char to_change() const { return sym_to_change; }
	bool sym_state() const { return state_by_sym; }
private:
	NXString pr_name = "degault";
	int pr_iter = 0;
	int start_path_value = 0;
	bool canceled = true;
	bool toggle_val = false;
	char sym_to_change = 'x';
	bool state_by_sym = false;

    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::StringBlock* string0;// Block type: String
    NXOpen::BlockStyler::StringBlock* string01;// Block type: String
	NXOpen::BlockStyler::StringBlock* string02;// Block type: String
	NXOpen::BlockStyler::Toggle* toggle0;// Block type: Toggle
};
#endif //MY_MENU_H_INCLUDED
